### PR TITLE
Capture redux state

### PR DESCRIPTION
**Pull request by milotoor**
There are two major changes here: the capturing of redux state, and converting the monitor to operate as a web worker. During the review of this PR, you may find it helpful to simultaneously review the [webapp PR](https://github.com/FabricGenomics/omicia_webapp/pull/2766/files); that PR is substantially larger, however, so don't get lost.

## Redux State
This was the main reason for embarking upon this venture, but ultimately consumed less time than the web worker conversion. Capturing redux state is relatively simple: when debugging production code, I want to know what the state looked like before the error, and what actions had recently been dispatched to the store. We now record both of those things.

## Web worker
Converting the monitor to operate as a web worker is something I've wanted to do for a while. The benefit of it is straightforward: there's no more 10 seconds of lag whenever the user triggers an exception. The stack trace processing is somewhat CPU intensive, but now it happens in another thread so it doesn't have any impact on UX.

With that said, the implementation was anything but straightforward. For one thing, not all browsers support web workers, so we can't just write the monitor to work exclusively in a worker environment. Hence, code that wants to communicate to the monitor has to go down one of two paths: either talk directly to the monitor (if it's running in the main application thread, as it will do when the browser doesn't support web workers) or pass serialized messages to the web worker which then interfaces with the monitor. Right now that forking of behavior is happening in the webapp (see [here](https://github.com/FabricGenomics/omicia_webapp/pull/2766/files#diff-b8e101b9f704d1c8c30af37531b3555a) and [here](https://github.com/FabricGenomics/omicia_webapp/pull/2766/files#diff-1ca776e250816f298c4c939ede7b947e)), but in retrospect I think it would make more sense for that to happen here... I'll discuss more about this in the other PR.

On top of that, there are basic limitations inherent in web workers. Previously, the monitor relied on receiving the exception from the web application in order to process it; however, a JS exception can't be communicated to a web worker-- it's just not allowed. So the interface for the monitor had to change pretty drastically: instead of taking the exception itself as input, it takes serializable pieces of the exception (i.e. the error message, the stack trace, etc.). This required pretty comprehensive changes to the monitor's interface.

### CODE REVIEW

**Comment by milotoor** [comment]
@marcofalcioni @coldzonemt this is ready for review

**Comment by UnquietCode** [comment]
@milotoor Have you ever thought about becoming a technical writer?  🤓

**Comment by milotoor** [comment]
@UnquietCode no, but I'd probably be good at it

**Comment by marcofalcioni** [comment]
my brain hurts.

**Pull request merged**
